-- Migration: OWASP Top 10 2021 → 2025 category rename
-- Renaming order avoids duplicate enum value names at any point in the sequence.

-- 1. A04_INSECURE_DESIGN → A06_INSECURE_DESIGN (frees A04 slot)
ALTER TYPE "OWASPCategory" RENAME VALUE 'A04_INSECURE_DESIGN' TO 'A06_INSECURE_DESIGN';

-- 2. A05_SECURITY_MISCONFIGURATION → A02_SECURITY_MISCONFIGURATION (frees A05 slot)
ALTER TYPE "OWASPCategory" RENAME VALUE 'A05_SECURITY_MISCONFIGURATION' TO 'A02_SECURITY_MISCONFIGURATION';

-- 3. A03_INJECTION → A05_INJECTION (A05 slot now free)
ALTER TYPE "OWASPCategory" RENAME VALUE 'A03_INJECTION' TO 'A05_INJECTION';

-- 4. A02_CRYPTOGRAPHIC_FAILURES → A04_CRYPTOGRAPHIC_FAILURES (A02 and A04 slots now free)
ALTER TYPE "OWASPCategory" RENAME VALUE 'A02_CRYPTOGRAPHIC_FAILURES' TO 'A04_CRYPTOGRAPHIC_FAILURES';

-- 5. A06_VULNERABLE_COMPONENTS → A03_SUPPLY_CHAIN_FAILURES (A03 slot now free)
ALTER TYPE "OWASPCategory" RENAME VALUE 'A06_VULNERABLE_COMPONENTS' TO 'A03_SUPPLY_CHAIN_FAILURES';

-- 6. A10_SSRF → A10_EXCEPTIONAL_CONDITIONS
ALTER TYPE "OWASPCategory" RENAME VALUE 'A10_SSRF' TO 'A10_EXCEPTIONAL_CONDITIONS';
